---
proxy-providers:
  ANTI MALAK PAKET UTAMA:
    type: file
    path: "./proxy_provider/tester-akrab.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 100
proxy-groups:
- name: ALL INJECTION
  type: url-test
  disable-udp: false
  use:
  - ANTI MALAK PAKET UTAMA
  url: http://www.gstatic.com/generate_204
  interval: '100'
  tolerance: '100'
- name: PILIHAN
  type: select
  disable-udp: false
  proxies:
  - ALL INJECTION
  - DIRECT
  - REJECT
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
unified-delay: true
external-controller: 0.0.0.0:1080
secret: RULES
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - 192.168.8.1
  - 192.168.7.1
  - dhcp://"eth0.200"
  - dhcp://"wwan0"
  default-nameserver:
  - 192.168.8.1
  - 192.168.7.1
ipv6: false
profile:
  store-selected: true
  store-fake-ip: true
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- SRC-IP-CIDR,192.168.1.1/32,DIRECT
- SRC-IP-CIDR,198.18.0.1/32,DIRECT
- RULE-SET,Direct,DIRECT
- RULE-SET,Reject,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- MATCH,GLOBAL
rule-providers:
  Reject:
    type: file
    behavior: classical
    path: "./rule_provider/Reject.yaml"
  Direct:
    type: file
    behavior: classical
    path: "./rule_provider/Direct.yaml"
